clubData =[
  {
    "clubName": "Mechanical club",
    "clubID": 1,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello Fillot !!! <br>If you want to tinker or are just interested in mechanics, feel free to come to the mechanical club! We currently repair most of the abandoned bikes that are put for rent at the MEUD residents. So if you have a problem with your bike, our team will be there to help you get it running again! We also have other projects in mind and look forward to hear yours! Our team of enthusiasts will surely help you make them reality! <br>Our space is located in the Lavoisier garage behind the entrance by the stairs. <br>See you soon and have a great time!",
    "clubImage":"../../img/logoAsso/meca.png",
  },
  {
    "clubName": "Video club",
    "clubID": 2,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"The video club is part of the BDA of IMT Lille Douai. Its main role is to retrace all the events of the school's associative life and to archive the best memories of the current year. These moments are shared with the students threw the “JT” that we air 3 to 4 times a year in the Nicolas’ room. A room on the third floor of the Lavoisier residence is dedicated to our club. This room allows us to leave our equipment (cameras, drone, green background...) and to make our videos.",
    "clubImage":"../../img/logoAsso/video.png",
  },
  {
    "clubName": "Dance with mines",
    "clubID": 3,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillotte, Fillot,<br>You've been sitting on your ass for two or three years now? This time is over, because this year, you're going to dance. Whether you're a beginner, motivated to set the dance floor on fire, or an experienced dancer, join Dance With Mines, the school's dance club! We'll teach you our classiest passes, which you'll be able to use at the school’s parties.<br>However Dance With Mines is much more than that: it's the committee that will accompany you in your practice, for any dance style you choose.<br>Besides, Dance With Mines wants diversity! If you are fond of tango, street, salsa, modern jazz, minuet (why not) or any other dance, the club will welcome you with pleasure so that you can share your passion with everyone ! In short, you understood, Dance With Mines is about dancing and good mood. Cannot wait to meet you",
    "clubImage":"../../img/logoAsso/dance.png",
  },
  {
    "clubName": "Club théâtre",
    "clubID": 4,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillotte, Fillot,<br>The Drama Club invites you to come and share your perhaps hidden acting talents with an exceptional troupe! Whether you're a veteran or a complete beginner, an improv fan or a classical theater fan, the best club in the world welcomes you ! This year, you'll have the honor of revealing the full extent of your talent on stage during our various organized performances and improv games. You will also be able to perfect your theatrical culture by attending different representations in our superb Douaisian theaters. You will also get to spend an excellent evenings in our company! hoping to see you in the troop as soon as possible,<br>The theater club",
    "clubImage":"../../img/logoAsso/theatre.png",
  },
  {
    "clubName": "IMT'ERNATIONAL",
    "clubID": 5,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello, Fillots! It's great to see you on campus! IMT'ERNATIONAL welcomes you! <br>What is IMT'ERNATIONAL? It's simply the School's international student committee. If you come from somewhere else and you're eager to settle in France, we're here for you! <br>Each year, we welcome a hundred international students from all over the world. Who bring with them a wide range of skills and talents that will enrichs our community at IMT. During your first year, we will be your privileged contact for all the administrative procedures to help you get started with your student life! <br>But we won’t just stop there! During the school year, we’ll organize events with the other clubs that will be internationally themed. where you get to know each other better and meet other students from different cultures, in parallel to discovering all the everyday French lifestyle!<br>If all this tempts you, don't hesitate to join us, we are looking forward to seeing you! <br>IMTER'Kiss",
    "clubImage":"../../img/logoAsso/imternational.png",
  },
  {
    "clubName": "Choir",
    "clubID": 6,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Chœur d'Arti-show has no other vocation than to make you vibrate! <br>Whether you are a neophyte, an experienced soloist or an occasional chorister, the doors of this fantastic club are wide open to you. We will be there to accompany you with kindness in your desire to take flight, alone on stage, or in the heart of the Douai choir... <br>Don't be afraid to launch yourself forward, we're only waiting for you! Our ambition is to help you, and to accompany you on the very nice events such as the Gala, the Cabaret, the Jams. A session is planned every week for choir rehearsals on chosen pieces. <br>If you want to sing, whether in group or solo, stop hesitating and join us!",
    "clubImage":"../../img/logoAsso/choral.png",
  },
  {
    "clubName": "The fanfare",
    "clubID": 7,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"From the trumpet to the accordion, passing by the pipe or the violin, the brass band is a band of merry students of all levels and all horizons which give rhythm to the big events of the MEUD (cabaret, gala, art'scene...)..<br> Do you want to play in a group with no stress ? Do you want to play your best solos or simply put together some tracks that will blow our minds away? Then don't hesitate and join our ranks! Nothing could be simpler, you just have to come with a good mood and we will provide the rest! (bringing an instrument is a plus)",
    "clubImage":"../../img/logoAsso/fanfar.png",
  },
  {
    "clubName": "Supporters",
    "clubID": 8,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"A match is played on and off the field, so it is only when players and supporters are together that the magic will happen and Douai will triumph. So if the sound of the nets makes you vibrate, if at each action your heart can capsize, don't hesitate any more, come and join us, get drunk with the fervor of the Douai’s kop. By joining our ranks, you will move wherever our school’s delegations are sent to defend our colors, proclaim your love to the referee and to the opposing players.<br />Unite your voice and we will make you a true supporter.<br />Fumigene'kiss<br />",
    "clubImage":"../../img/logoAsso/supporter.png",
  },
  {
    "clubName": "Cotrad",
    "clubID": 9,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"IMT Lille Douai is a school with a unique atmosphere and over 150 years of history. I might as well tell you that we have a lot of traditions. Some funny, some solemn and some strange. So here is a club to manage all that: the CoTrad or Tradition Committee.<br />And then we have another role: that of taking care of the relations with the Alumnis (thus it’s a good plan if you want to find an internship) with whom we organize numerous events all year long, with quite a lot of new ideas ! <br />We also manage all the archives of the school life and believe me, the school has seen a lot of strange things over the years.<br />So, boys or girls, come and join the CoTrad soon, where meetings rhyme with “aperitif”.<br />Tradi'kiss",
    "clubImage":"../../img/logoAsso/cotrad.png",
  },
  {
    "clubName": "Rugby club",
    "clubID": 10,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Welcome you lovers of the oval ball or of its 3rd half time, I’m proud to present to you the XV of the black faces! <br />First of all know that the physical qualities are clearly not of the essence has it is not with my 2m10 and 120kgs that they call the “Shrimp” <br />The most important thing is a frank spirit of teamwork and a good beer after every match. It is ESSENTIAL for the recovery, as it assures us no headaches! <br />Know that we stand out by our results (only 1 try scored in 2018-2019 and yes I was part of the team ...) Nevertheless we are progressing. Thanks to the 3A we have been able to put 2-3 spankings since! But now we need you fillot(e) for this season whether you played at the highest level or that you have two left hands!<br />The big family of the XV of the black faces welcomes you!",
    "clubImage":"../../img/logoAsso/rugby.png",
  },
  {
    "clubName": "Imterlude",
    "clubID": 11,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Imterlude is the radio club of the school! It's a very young association where there is everything to create and imagine. All ideas are good to take, so whether you're a connoisseur or not, if you like chatting behind the microphone or if you have a podcast topic that you like, don't hesitate to join us! Our little association has the ambition to create a real family ready to animate the airwaves of the MEUD <3",
    "clubImage":"../../img/logoAsso/imterlude.png",
  },
  {
    "clubName": "Comité musique",
    "clubID": 12,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillote, fillot, Music is part of your life? You are in need of concerts? Have you abandoned your instrument during your two or three years of prepa school? Then the music committee will allow you to rediscover that forgotten flavor and express your talents with the help of our two music rooms and our instruments! Whether you play jazz, rock, metal, classical, rap or pop, you are welcome to use both rooms at any time of the day or night! Guitars, pianos, drums, amps and microphones... Whatever your style, alone or in a group, you will be able to express your artistic soul and unleash your creativity! The committee will be happy to meet you and discuss music with you... and why not meet you during the different concerts and jams of the year where you can express your talent!<br />Amnéziki'kiss",
    "clubImage":"../../img/logoAsso/amnezik.png",
  },
  {
    "clubName": "ZeGreenPeas",
    "clubID": 13,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Dear fillote, dear fillot, With the ZeGreenPeas team, we are fans of our little blue planet (without which we would not be much) and we want to preserve it to benefit a maximum of people! So what better way to raise awareness about environmental protection than to start with the beautiful city of Douai, crossed by the Scarpe river, home to a vast ecosystem of mattresses and other exotic fishes... if you look hard enough, you might even meet little forest spirits ("kodoma" for Miyazaki's specialists) there. Our first objective is to raise awareness among all students (not only the ones who don't sort their garbage). We organize conferences as well as clean walks, or small DIY workshops to learn how to make your own products. We establish partnerships with eco-responsible shopkeepers which also allows us to propose organic baskets and many other things you might need :) On top of that, (and yes, cleaning the Scarpe is nice but it's not enough) we set up inter-school events and we try to have a bigger impact by participating in a lot of different workgroups that might interest you. If you too dream of being a super sweet potato and saving the planet, or if you just want to do cool things to contribute to the ecological transition, don't hesitate to join our team!<br />GreenKiss' for our little peas,",
    "clubImage":"../../img/logoAsso/greenpeas.png",
  },
  {
    "clubName": "Club Sépia",
    "clubID": 14,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hey fillot or fillote,<br />I am very happy to introduce you to the Sepia club, it is the school photo club. It is here to immortalize your often forgotten evenings. More seriously, our goal is to capture the highlights of life at IMT Lille-Douai, like the gala or the cabaret. The club is open to photographers of all levels, whether you are a beginner or an expert, even if you don't own a camera you can borrow one from the club. During the year, we will immortalize the numerous events of the school. From parties to sports events, nothing will escape our attention. For beginners, workshops will be organized during the year, notably how to use the manual mode. But also outings in Douai or Lille open to all!<br />Come and develop and share your passion !",
    "clubImage":"../../img/logoAsso/photo.png",
  },
  {
    "clubName": "L’Artelier",
    "clubID": 15,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"The Art'elier club allows all students to reveal their inner artist and share their creative ideas. The goal is to learn the arts together in a friendly atmosphere, using all techniques, drawing, painting and sculpture. The club organizes discovery workshops, drawing evenings and other creative challenges such as inktober! We hope you'll come and color your hands and heart with us...",
    "clubImage":"../../img/logoAsso/dessin.png",
  },
  {
    "clubName": "Téléthon",
    "clubID": 16,
    "parrent": "BDH",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillote, Fillot,<br />As its name indicates, the telethon committee is in charge ... THE TELETHON! This association supports research against rare diseases and helps patients in their fight. During a week full of events that takes place at the beginning of December, you can join our team to bring back a maximum of pepettes to the cause! We need hands to help us with the kitchens to prepare breakfasts, or to paint pretty decorations for our parties! Any excuse is good to join us. It will also be a great opportunity to introduce you to the school's association. A few weeks before the BDX campaigns, you will get a taste of this extraordinary adventure! Your motivation is welcome to support us in this beautiful project and we will welcome you with great pleasure.<br />The telethon committee",
    "clubImage":"../../img/logoAsso/telethon.png",
  },
  {
    "clubName": "Cousu’mines",
    "clubID": 17,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"The Cousumines club is the school's fashion club, attached to the Bureau Des Arts. This club's objective is to promote creativity at the Maison Des Élèves by setting up artistic creation and retouching workshops, etc. This year we have many projects such as organizing a dressing sale at the MEUD, or fashion shows during the GALA...",
    "clubImage":"../../img/logoAsso/cousu.png",
  },
  {
    "clubName": "Egal’IMT",
    "clubID": 18,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Welcome to all!<br />Through the Egal'IMT committee, engineering students celebrate diversity, encourage self-expression and contribute to making our school, IMT Lille Douai, a place of openness and tolerance. In direct collaboration with the administration and the IMT school network, our committee solicits students through projects, workshops and round tables to raise awareness of ordinary discrimination, sexism, racism, LGBTphobia... We are committed to accompanying and supporting the students. The committee is open to all and with the help of each of you, we aspire to evolve towards an ever more healthy and tolerant environment, to contribute to the openness of tomorrow's engineers. So, fillot and fillote, without further ado, come join the committee to build a more just and inclusive society.",
    "clubImage":"../../img/logoAsso/egalimt.png",
  },
  {
    "clubName": "Oenologie Club",
    "clubID": 19,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Lover of all kinds of alcohol: beer, p'tit jaune, vodka? You won't be able to taste any of that. And yes, the wine club is about tasting good wine! You will be invited to our tasting sessions (screw the covid). You will be able to treat your taste buds with quality wine, cheese and charcuterie! But above all, you will share a convivial moment with the committee and learn more about wine. Don't miss our events or you will regret it!",
    "clubImage":"../../img/logoAsso/oeno.png",
  },
  {
    "clubName": "Popcorn Club",
    "clubID": 20,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hi future fillots and fillotes!<br />The Douai Film Club is getting a makeover this year to welcome you in our brand new screening room, entirely renovated during the summer (at least we hope so as we write this...). Finished or not, you are welcome in this room where weekly screenings will be held, followed by discussions on the film for those interested. Whether you're a movie buff or just curious, whether you're a fan of auteur films or a big fan of blockbusters, don't hesitate to drop by the club. We'll even be happy to screen your proposals. Popcorn Club also has many projects for this year, the most ambitious being the realization of a Film Festival in Douai. We will need motivated people to make this project a success, so come and join us! And if the weekly screenings are not enough to quench your thirst for movies, the Cinéma Tandem is only a 10min walk from the Meud and offers a very varied program, cheap and entirely in VO for the purists. We hope to see you soon!<br />Ciné'kiss",
    "clubImage":"../../img/logoAsso/popcorn.png",
  },
  {
    "clubName": "Club Poker",
    "clubID": 21,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello to you young miner!<br />If you are reading these lines today, it's for a very simple reason: I have a great opportunity for you to finance your beers. Indeed, the IMT poker association opens its doors to you with great players ready to play with you in a good atmosphere. Whether you're a total beginner or one of those famous 'sharks', a chair and chips will be waiting for you. If you're still hesitating to join us, well, for me, the question is quickly answered.",
    "clubImage":"../../img/logoAsso/poker.png",
  },
  {
    "clubName": "Junior-Entreprise ARTEMIS",
    "clubID": 22,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillote, Fillot,<br />Do you want to be part of a meaningful project? Do you have ambition? You want to boost your CV while joining a close and dynamic team? Then ARTEMIS is made for you! Association functioning as a company, the Junior of the school will put you in contact with the professional world and will help you to develop your skills. Prospecting, Follow-up of missions, Communications, Computer science, Secretary Duty/Human resources, Treasury, Quality Management... There is something for everyone! ARTEMIS will also allow you to join the biggest student movement in France and to participate to regional and national congresses of madness! Joining ARTEMIS, it is above all to integrate a united and highly motivated team at the service of the students of the school. Missions, trainings, afterworks, ARTEMIS Week, team-building activities and much more! If you want to take responsibilities and become professional, all in a good mood, don't wait any longer and join us!",
    "clubImage":"../../img/logoAsso/artemis.png",
  },
  {
    "clubName": "Le Caméléon déchaîné",
    "clubID": 23,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Living in the shadows, the Caméléon Déchaîné is a tough animal to watch. Once a month, he comes out into the open to deliver the stories of the Meud to those who may have missed the various events, or to those who wish to discover them in a different way. But his role is not only limited to that. Each month, it will make you discover a theme under many aspects, arousing your curiosity. But le Caméléon never goes out alone, his faithful sidekick, the GeckoZen, living on the web, will contain everything he could need for the Caméléon: additional articles, full interviews, archives ... If you want to discover the conception of a newspaper, then you are welcome! You will be able to participate in a lot of interesting things: writing, editing, layout, drawing or even communication! Of course, the Caméléon is above all about sharing, so we're making room for you to share your passions with us! So don't hesitate any longer and join the Caméléon Déchaîné!",
    "clubImage":"../../img/logoAsso/cameleon.png",
  },
  {
    "clubName": "Douai Moustache Club",
    "clubID": 24,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"This message is addressed to some young people who have not forgotten what real class was. Indeed I have the honor to introduce you to the Douai Moustache Club or DMC for the intimate ones. The most important association by far, the one that will give you the opportunity to wear your most beautiful moustache during the month of November as part of Movember to fight against testicular cancer, prostate cancer and others. This will be an opportunity to seduce beautiful ladies thanks to this dashing moustache that you will wear proudly, an opportunity to see who is a gentleman like we do not make any more, an opportunity to laugh by making fun (nicely or not according to affinities) of the few young boys totally hairless who dare to show themselves in November. So, prepare your razor, your lather and your best aftershave because if you are not impeccably shaved during this magical period, thus showing your contempt for this noble cause, some beauticians and amateur beauticians will take care of you. In short, think of your father and do this for him, for his testicles and prostate, and participate in Movember with the DMC.",
    "clubImage":"../../img/logoAsso/moustache.png",
  },
  {
    "clubName": "Bar",
    "clubID": 25,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello to you fillot!<br />I have the honor to introduce you to the bar. An essential place of life of the meud which we missed a lot last year in which you will have the opportunity to spend memorable moments that you will also forget sometimes. The beer flows freely and is served by a team of twenty or so morons who have been through some fuzzy and sometimes dark moments, but mostly very fun. No matter who you are, you'll find happiness, you'll meet people and maybe you'll even fall in love with this place. You already wish you were part of it? One thing at a time. You will see during the year how to move to the other side of the bar if you ever want to. But this little presentation can't really show you what the bar is all about, so we're counting on you to come and buy yourself a few beers and see for yourself what the bar really means to the MEUD.",
    "clubImage":"../../img/logoAsso/soon.png",
  },
  {
    "clubName": "IMTLD E-sport",
    "clubID": 26,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"If you are looking for the best way to furnish your confinement, if you are a fan of video games, esport or just an aficionado of the sofa consoles, don't wait any longer, the IMTLD E-Sport club is here for you! We propose to make the link between the different IMT sites through video games, in order to allow gamers to meet and organize IRL or online gaming sessions. In addition to offering participation in various inter-school tournaments on a national scale, we also organize our own events centered around video games. We are active on the twitch platform where we comment on our teams' matches to allow everyone to enter the esport world and share the atmosphere. Whether you're a hardcore CS:GO player, a Domingo expert on League of Legends, or you just want to play a good old Mario Kart or Smash Bros with your friends, the E-Sport club is for you!<br />So don't wait any longer and join IMTLD E-Sport!",
    "clubImage":"../../img/logoAsso/esport.png",
  },
  {
    "clubName": "Comité CCE",
    "clubID": 27,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hey, fillot and fillote!<br />You want to spend a week at the seaside, in the biggest student sports competition in Europe? But also to have drinks and big parties with your friends, punctuated with some chill moments? Then embark on the 54th EDHEC Boat Race! The CCE is 3200 students, 9 days of sports and parties in the middle of April. Whether you're a seasoned athlete or a party animal, the CCE is sure to please you. Indeed, even if the fame of this event is due to its week of regatta called the Sea Trophy, there are other things to discover! Whether you are rather 'quiet' with the Sand Trophy, which gathers team sports in 'beach' mode with its friendly bar... Or daredevil with the Earth Trophy, military courses that will test your endurance with climbing, trails, mountain biking and others. This trophy is for those who want to give it their all, all with a strong team spirit. The CCE is a great experience to test (all) your limits. See you in the water! Salty kisses, Pierrick aka Pipi for friends",
    "clubImage":"../../img/logoAsso/cce.png",
  },
  {
    "clubName": "IMTremplin",
    "clubID": 28,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello fillot, fillote!<br />You will discover in these few lines the best BDA club of this year, namely the IMTremplin! 'But what is the IMTremplin?' It's a musical springboard made up of groups of musicians from the school. Our role is to train the bands, coach you as well as get you to perform in outside bars. We plan to give the winners a nice reward as well as to play at the festival of the festoch committee during their event gathering 3000 people. This year the edition will be done with the site of Lille, ending on a beautiful common final that will not fail to be caliente ;)) If you hung up your instrument or your voice during your prep school or if you want to experience amazing concerts again, don't hesitate and come to the IMTremplin! Plus, it's a great opportunity to learn a new instrument! Our coaches will be there to help you! If you have any questions, don't hesitate to contact me (Pierrick who is the secretary at the CAPA) and the other members of the staff. We're waiting for you to participate in the events as a musician and as a member of the audience.<br />IMTremplin'kiss,",
    "clubImage":"../../img/logoAsso/tremplin.png",
  },
  {
    "clubName": "Comité Cartel",
    "clubID": 29,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"3 STEPS FORWARD! 3 STEPS BACK!<br />IT'S THE MINES OF DOUAI WHO ARE AT THE CARTEL<br />Fillote, Fillot, get ready because the cartel is the biggest event of your first year. Whether you have sports in your blood or are a fan at heart, come and defend your school's colors during 4 days of competitions and parties. Bringing together all the schools in the Mines Telecom network in France and abroad, this year's competition will take place in Saint-Etienne. We can't be satisfied with our third place in the second last edition, our goal is to reach the first one! So train all year long to be selected and come and live the best weekend of your life! The program: during the day you will either be on the field giving it your all in more than ten disciplines, or in the stands chanting the Paillardier and cheering on the school! All this will be enhanced by parties where you will have to put on a fiery atmosphere to win the atmosphere prize! In addition to spending 4 crazy days, the cartel is also the opportunity to see your friends who have integrated participating schools and to have fun with them! So come, we're waiting for you ! Finally, we will be organizing several small events during the year and we are looking for new people to help us and pass the baton. Don't hesitate to join the association!",
    "clubImage":"../../img/logoAsso/cartel.png",
  },
  {
    "clubName": "Club Sono Parkin’Son",
    "clubID": 30,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"The Sono club is the club which takes care of putting a quality music during the evenings. It is above all, a club of music lovers. Here, we learn to set up from A to Z the sound system, from the turntable to the speakers, through the lights, and of course we also teach the filler to mix! The goal of the club is to make a maximum of people dance during our parties thanks to our music, our DJs and our quality equipment!",
    "clubImage":"../../img/logoAsso/parkin_son.png",
  },
  {
    "clubName": "IMT Lille Maurice",
    "clubID": 31,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Want to get away from it all and discover board sports? Then IMT Lille Maurice is there for you! Come and have fun with your friends and discover many different disciplines on land and at sea! Here we love surfing, kiteboarding, sailing, sand yachting and we love skating, rollerblading and ice skating! During the year, many outings will be organized in order to make the association live. You only need to be a BDS contributor to be able to participate. On the other hand, the activities that require less logistics like rollerblading or skateboarding, will be done in our dear city of Douai, and will be daily if there are motivated people. If this presentation convinced you, don't hesitate to join our social networks (IMT-LilleMaurice) on facebook and instagram, in order to be informed of the next events and discover our crazy team! See you soon for more adventures, <br />Gliss'kiss !",
    "clubImage":"../../img/logoAsso/maurice.png",
  },
  {
    "clubName": "Chess’Mate",
    "clubID": 32,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello to you young fillot or fillote,<br />You saw The Queen's Gambit on Netflix and it made you want to play it? We have the solution for you! Chess'Mate is the school's chess club, freshly created to bring together the many players in the group. Come and join us to live a year in black and white Are you a beginner? No problem! We'll be there to help you progress, and you'll surely find people in the same situation as you On the contrary, you are an expert? Come and demonstrate it during the tournaments we will organize throughout the year.<br />Don't hesitate, we are waiting for you",
    "clubImage":"../../img/logoAsso/echec.png",
  },
  {
    "clubName": "Pompoms",
    "clubID": 33,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"My dear boy, my dear girl,<br />Soon you too may be cheered by the famous chant: 'FREE THE POMPOMS!' Pompoms, rhythmic choruses and smiles to fall, you will find the pompoms at various events throughout the year (Gala, Cartel and much more!) Whether you're a man or a woman, a dancer, a backflip pro or just full of energy and good humor, there's a place for you in this loving family and a great outfit for men and women! Adorned with our purple and silver pompoms, the pompoms will be there to represent your beautiful school colors and make the competitors fall for our charm!",
    "clubImage":"../../img/logoAsso/pompom.png",
  },
  {
    "clubName": "IMTalks",
    "clubID": 34,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Greetings to you, dear Fillot!<br />Do you want to participate in sharing ideas and knowledge on a variety of topics such as art, science, or culture? IMTalks is here for you! I am honored to introduce you to the club that organizes TEDx IMT Nord Europe. Yes, the school has been hosting its own TEDx for 5 years now. How classy is that? Last year, because of the health situation, the TEDx IMT Lille Douai could not take place... But it's only a postponement for this year! We are so keen to bring speakers to the north of France that we have decided to organize conferences in addition to TEDx IMT Nord Europe for the first time. We need your help to make the first edition of our conferences perfect, and to make TEDx IMT Nord Europe as cool and interesting as the previous years. So don't wait any longer, join our team!<br />See you soon,",
    "clubImage":"../../img/logoAsso/talks.png",
  },
  {
    "clubName": "Club robotique",
    "clubID": 35,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillote, Fillot,<br />The Robotics Club of the school is the place to be for all tinkerers and electronics enthusiasts. Whether you just want to discover robotics in a good atmosphere, or improve your skills in areas such as electronics, programming, 3D printing or even artificial intelligence (if you're really into it), you'll find what you're looking for at the club, whether it's among the projects underway or in preparation. You could even start your own project! To accompany you in its realization by giving you access to the tools of the club or the FabLab is also one of our missions. For this year, we count a lot on your imagination for the post-Covid relaunch of the club, so don't hesitate to come up with good ideas and to join us for ever crazier and more ambitious projects. Of course, you can also join us in our projects to repair damaged equipment or to create small autonomous robots and other crazy machines. So don't hesitate any longer, if these few lines have titillated something in you (we don't want to know what) come and see us at 2 PA and discover the club from the inside!",
    "clubImage":"../../img/logoAsso/robot.png",
  },
  {
    "clubName": "Weski",
    "clubID": 36,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hi fillot and fillote,<br />Are you interested in participating in one of the school's biggest events? Then come and join us in a great ski resort to show us your skiing or snowboarding skills! Your Weski committee will organize a crazy week of parties, ski days and after-ski events! You will also have the possibility to have ski and snow lessons every morning thanks to your Weski team who will be even fresher than the snow! Don't forget to book your week from February 12th to 19th. We'll have time to meet at the Weski evenings to answer all your questions over good mountain food! But remember that places are limited and are called by shotgun...",
    "clubImage":"../../img/logoAsso/weski.png",
  },
  {
    "clubName": "Gala",
    "clubID": 37,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Fillote, Fillot,<br />This year you will discover the IMT Lille Douai Gala and it will be the most prestigious event you will experience here! During an evening that will take you to the end of the night, nearly 1000 people will gather in a dazzling setting to party and celebrate all the talents of the school.<br />This is an opportunity to bring together more than six generations of students around the traditional dinner show before enjoying a unique evening brought to you by the school's best DJs as well as professionals.<br />Keep an eye out for the Gala, because this is the event you don't want to miss! Whether you are an artist from the Douai, Lille, Valenciennes, Alençon or Dunkerque campuses who wants to show off your talents during the show; a party animal who misses the big parties; or if you want to go behind the scenes of an exceptional organization, the Gala will meet your expectations!<br />The numerous students of the Gala committee will be there to accompany you, answer your questions and reveal the theme of the year (still kept secret for the moment) so don't hesitate to contact them",
    "clubImage":"../../img/logoAsso/gala.png",
  },
  {
    "clubName": "La Mine aux merveilles",
    "clubID": 38,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Let's set the scene: you have just entered your new school, you are walking through the corridors of the Lavoisier residence. While you are wandering in the fourth floor, your eyes are quickly attracted by the bottom of it. It wasn't an unpleasant hole, dirty and damp, filled with bits of worms and an oozing atmosphere, it was a Mine filled with various and varied treasures. Your gaze is first fixed on a shelf where a multitude of board games are displayed. You then notice a large bookcase overflowing with comics and mangas. Listening to you, you realize that the Mine is full of other treasure hunters who are also taking advantage of the various treasures offered by this place, a little outside the reality of the MEUD. To put it simply, the Mine aux Merveilles is the association of board games, role playing games and comics/Manga of the Douai site. Whether you are a veteran or a beginner, whether you want to borrow games to play with friends or just to read a comic book in a corner, whether you just want to play one night at the local game room or to organize role-playing games within the Meud, everyone will be able to find a golden nugget in the Mine.<br />Yours playfully,<br />The bureau of La Mine aux Merveilles",
    "clubImage":"../../img/logoAsso/merveille.png",
  },
  {
    "clubName": "Club cirque",
    "clubID": 39,
    "parrent": "BDS",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Do you dream of flying through the air and performing dizzying tricks? The circus club is for you! This reborn club will be delighted to welcome you and share with you the passion of the circus. Whether you are an amateur or a curious beginner, you will be able to come and use our equipment (trapeze, fabric and others to come) in one of the gyms in Douai. The objective: to discover the circus arts and prepare a number to shine at the evening of the year: the GALA!",
    "clubImage":"../../img/logoAsso/cirque.png",
  },
  {
    "clubName": "Club débats",
    "clubID": 40,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello the MEUD!<br />You think you're a good speaker? Do you like to argue or are you just curious? The debate club is for you! We regularly organize discussions on various topics, and you are welcome to share your point of view and - especially - to defend it in front of others, but always in a good mood! So if you have a topic that's close to your heart, or if you want to put your talents to the test, come and say hello!",
    "clubImage":"../../img/logoAsso/debat.png",
  },
  {
    "clubName": "4L trophy",
    "clubID": 41,
    "parrent": "BDH",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"The IMT Lille Douai 4L Trophy club brings together students who want to take part in the 4L Trophy, which is the biggest student rally in the world with more than 1,200 crews, i.e. over 2,400 participants! This raid starts in Biarritz and ends in Marrakech, crossing Spain and the Moroccan desert, and all this in a Renault 4L of course!",
    "clubImage":"../../img/logoAsso/4L.png",
  },
  {
    "clubName": "Club des brasseurs",
    "clubID": 42,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"The one who says north of France says love of beer...yes the shortcut is fast but true! If you like to drink it then you will love to brew it. The club of the brewers of the mines is the club which will teach you all the cogs which hide behind the preparation of this soft nectar which can take multiple forms! With us, there is no pressure except in your glass... Brewing, tasting and aperitif are on the program so come and spend a good time with us, conviviality and sharing will be the order of the day and you will become a real malt and hop pro!<br />Bis'houblonux",
    "clubImage":"../../img/logoAsso/brasseur.png",
  },
  {
    "clubName": "Cuis’mines",
    "clubID": 43,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"To you, lover of good things, passionate about taste, magician of the ovens. You will have understood, in this association we know how to enjoy ourselves, and we enjoy it! Beginner, amateur, expert, chef: everyone is welcome (yes, even you who just want to taste sumptuous dishes without getting your hands dirty). This year, we will share with you written recipes and videos, there will be something for everyone, meat or fish lovers, vegetarian or vegan, sweet or savory, novice or experienced. Follow us on the networks to enjoy our products all year long. If all goes well, we will provide cooking workshops for those who wish to master more culinary techniques. You will be able to borrow freshly purchased kitchen equipment this summer. We will be preparing meals from scratch in collaboration with the wine and brew club and all Meudians will be invited! It goes without saying that we advocate tasteful, local, organic and seasonal cuisine! You will see that even with a student's scholarship, you can really enjoy yourself. For the most experienced among you, there will be an inter-school cooking competition. And as you are little gourmets, there will be many more surprises, but you will discover them during the year. Sweet kisses, you supremely beautiful people!<br />the Cuis'mines gang",
    "clubImage":"../../img/logoAsso/soon.png",
  },
  {
    "clubName": "Festival",
    "clubID": 44,
    "parrent": "BDA",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription": "Welcome to the association which gathers only music lovers, festivals, thrills and pure fun. Our goal? To organize the first edition of an open air music festival, around Lille. Our ambition? Not the least: 2 stages, 7 professional artists, as many amateur artists, an audience of 3000 people, stands galore and potentially the biggest event of the school. That's all there is to it. If you are motivated, enterprising (because yes we are talking about the first edition, so the creation of this festival), passionate about the same thing as us and that you see things in big, this association is made for you! We will not reveal you yet the name nor the logo of our festival, but especially do not worry fillot, they will arrive very soon We can't wait to let you know the program of this festival, which we hope will soon compete with the biggest student festivals of France and Navarre!",
     "clubImage":"../../img/logoAsso/soon.png",
  },

  {
    "clubName": "Eurotandem",
    "clubID": 45,
    "parrent": "BDH",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Hello to you, fillot and filote!<br />You may have already met these beautiful, strong and valiant students pedaling for more than fifteen days in tandem, against the wind, the sun or the rain, to promote blood donation in the four corners of France? These students are part of the Eurotandem! But what is Eurotandem? It's a unique association of about thirty students that has existed since 1991. This beautiful band of thirty buddies formed of first and second years leaves to make a tour of France on their faithful steeds, their magnificent tandems, for more than fifteen days during the vacations of April to promote the donation of blood. With this crazy experience, you will surpass yourself both humanly and physically. We promise you that you will come out of it totally transformed! First of all, your buttocks will be very, very sore, you will have thighs worthy of the greatest athletes, but above all, you will have unforgettable memories in your head. You will discover and enjoy a lot of magnificent landscapes, each one more grandiose than the other. You will also meet a lot of blood donation volunteers after having collected pledges and with whom you will spend warm moments. But the Eurotandem is above all a family, thirty people with whom you will spend two weeks to enjoy, pedal, motivate, surpass themselves, meet, share, taste, laugh... As you can see, you're going to form strong bonds during the Euro. So if you want to participate in a unique sporting and human adventure, come and ride a tandem with us! Don't hesitate to come and ask us questions, you'll probably recognize us thanks to our slightly dirty cycling shirts. Kisses on your buttocks,<br />Euro'love",
    "clubImage":"../../img/logoAsso/eurotandem.png",
  },
  {
    "clubName": "Air",
    "clubID": 46,
    "parrent": "BDE",
    "facebook": "N/A",
    "insta": "N/A",
    "clubDescription":"Whether in your rooms or in the basement of the MEUD, AIR is everywhere. Who are we? We are an association passionate about computer science in general. We touch new technologies, programming, servers, cybersecurity, data science, etc. What do we do? We take care of and host association websites with the hacklab ("l'AIR" of Lille). But that's not all! We are the main interlocutor between the students and the Direction des Infrastructures et Système d'Information (You will often shout its name during your exams from home). As such, we manage the aliases of the different offices, the hosting of a Gitlab and the maintenance of different services. We help students in case of computer problems. During the summer, we organize the sale of cables and RJ45 adapters at reduced prices, and during the year, we play, discover and code, while having fun! With our servers, we can also organize LANs with the esport club, and we can also organize code competitions for the most daring. Who can join us? Whether you're a Shell expert, a graphic designer, a programmer in your spare time, or just interested in computers, you're welcome to join AIR. We will make you discover the joys and secrets of the computer world. In short, all the reasons are good so that we find you with us for an amazing year!",
    "clubImage":"../../img/logoAsso/air.png",
  }
];
